### ISSUE TITLE
HUD not renderig [BUG] 

### ISSUE THREAD

**Issue by rmcleveland** [dmrickey/token-action-hud-pf1#11]
**Describe the bug**
On most tokens on the scene the HUD does not render, all Player characters and most NPCs.

**To Reproduce**
1. Click on token
2. See error

**Expected behavior**
HUD Appears when token is selected.

**Screenshots**

**What version of TAH pf1/core are you using?**
pf1: 1.3.6
core: 1.4.14

**Additional context** 
Error from console:

actor-data.js:46 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'id')
[Detected 2 packages: token-action-hud-pf1, token-action-hud-core]
    at get isCurrentCombatant [as isCurrentCombatant] (actor-data.js:46:95)
    at #_buildCombat (hud-builder.js:232:32)
    at HudBuilder.buildSystemActions (hud-builder.js:31:31)
    at #u (token-action-hud-core.min.js:1:28514)
    at HudBuilder.buildHud (token-action-hud-core.min.js:1:26764)
    at async #at (token-action-hud-core.min.js:1:84594)

**Comment by dmrickey** [comment]
This should be fixed with 1.3.7
